workspace:
  path: src

pipeline:
  build:
    image: webhippie/hugo:latest
    pull: true
    commands:
      - make clean
      - make build

  docker:
    image: plugins/docker
    repo: gitea/blog
    tags: [ '${DRONE_BRANCH##release/v}' ]
    when:
      event: [ push ]
      branch: [ release/* ]

  docker:
    image: plugins/docker
    repo: gitea/blog
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  discord:
    image: appleboy/drone-discord
    webhook_id: ${WEBHOOK_ID}
    webhook_token: ${WEBHOOK_TOKEN}
    when:
      event: [ push, tag, pull_request ]
      status: [ failure ]
