workspace:
  base: /srv/app
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  build:
    image: webhippie/hugo:latest
    pull: true
    commands:
      - make clean
      - make build

  publish:
    image: lucap/drone-netlify:latest
    pull: true
    secrets: [ netlify_token ]
    site_id: b3cd7cc2-68be-4467-b3a6-38f1fdfa0cfc
    path: public/
    when:
      event: [ push ]

  discord:
    image: appleboy/drone-discord:1
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag ]
      status: [ changed, failure ]
