---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /srv/app
  path: src

steps:
- name: build
  pull: always
  image: webhippie/hugo:latest
  commands:
  - make clean
  - make build

- name: publish
  pull: always
  image: lucap/drone-netlify:latest
  settings:
    path: public/
    site_id: b3cd7cc2-68be-4467-b3a6-38f1fdfa0cfc
  environment:
    NETLIFY_TOKEN:
      from_secret: netlify_token
  when:
    event:
    - push

- name: discord
  pull: always
  image: appleboy/drone-discord:1
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    event:
    - push
    - tag
    status:
    - changed
    - failure

trigger:
  branch:
  - master

...
